version: "3.9"
services:
  papermc:
    build: .
    restart: "no"
    container_name: "papermc"
    environment:
      JAVA_ARGS: "-Xmx8G"
    volumes:
      - "./server:/server:rw"
      - "./backups:/backups:rw"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "25565:25565"
    # The following allow `docker attach minecraft` to work
    stdin_open: true
    tty: true